package ui;

import clases.Background;
import controladores.ControladorVeterinario;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Luis Gerardo Leon Ortega
 * @version 0.05.01
 */

public class PanelUser extends javax.swing.JFrame {
    
    private InternalPanelConfi ipc;
    private InternalPanelVacunasP ipvp;
    private InternalPanelVacunasG ipvg;
    private InternalPanelRegistros ipr;
    private InternalPanelBusqueda ipb;
    private InternalPanelCitas ipcits;
    private String id, user;
    private int lic;
    
    public PanelUser(String id, String user) {
        initComponents();
        this.id = id;
        this.user = user;  
        ponerBackground();
        verificarLicencia(id);
        ponerLicencia(lic);
        ponerActivacion();
    }
    
    public PanelUser(String id, String user, String posc){
        initComponents();
        this.id = id;
        this.user = user;
        ponerPosicion(posc);
        ponerBackground();
        verificarLicencia(id);
        ponerLicencia(lic);
        ponerActivacion();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMain = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblLic = new javax.swing.JLabel();
        lblRang = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        itemRegistrar = new javax.swing.JMenuItem();
        itemVacunasPerros = new javax.swing.JMenuItem();
        itemVacunaGatos = new javax.swing.JMenuItem();
        menuBuscarProp = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuConfi = new javax.swing.JMenu();
        itemLicencia = new javax.swing.JMenuItem();
        itemConfigCuenta = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemSoporte = new javax.swing.JMenuItem();
        itemInstructivo = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyVet v. 0.05.01");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource("/utilitarios/logo.png")).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout desktopMainLayout = new javax.swing.GroupLayout(desktopMain);
        desktopMain.setLayout(desktopMainLayout);
        desktopMainLayout.setHorizontalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        desktopMainLayout.setVerticalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("ESTADO DE LICENCIA:");

        lblLic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLic.setForeground(new java.awt.Color(204, 0, 0));
        lblLic.setText("Vencido / No activado");

        lblRang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRang.setForeground(new java.awt.Color(0, 153, 153));

        menuPrincipal.setText("Menu");

        itemRegistrar.setText("Registrar mascotas");
        itemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemRegistrar);

        itemVacunasPerros.setText("Vacunas de perros");
        itemVacunasPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVacunasPerrosActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemVacunasPerros);

        itemVacunaGatos.setText("Vacunas de gatos");
        itemVacunaGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVacunaGatosActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemVacunaGatos);

        menuBuscarProp.setText("Buscar propietario de mascota");
        menuBuscarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarPropActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuBuscarProp);

        jMenuItem1.setText("Tus citas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuPrincipal.add(jMenuItem1);

        menuBar.add(menuPrincipal);

        menuConfi.setText("Configuracion");

        itemLicencia.setText("Comprar licencia");
        itemLicencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemLicenciaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemLicenciaMousePressed(evt);
            }
        });
        itemLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLicenciaActionPerformed(evt);
            }
        });
        menuConfi.add(itemLicencia);

        itemConfigCuenta.setText("Configuracion de cuenta");
        itemConfigCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConfigCuentaActionPerformed(evt);
            }
        });
        menuConfi.add(itemConfigCuenta);

        menuBar.add(menuConfi);

        menuAyuda.setText("Ayuda");
        menuAyuda.setToolTipText("");
        menuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAyudaMouseClicked(evt);
            }
        });

        itemSoporte.setText("Soporte");
        itemSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemSoporteMousePressed(evt);
            }
        });
        menuAyuda.add(itemSoporte);

        itemInstructivo.setText("Instrucciones de uso");
        itemInstructivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstructivoActionPerformed(evt);
            }
        });
        menuAyuda.add(itemInstructivo);

        menuBar.add(menuAyuda);

        menuCerrar.setText("Cerrar Sesion");
        menuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCerrarMousePressed(evt);
            }
        });
        menuBar.add(menuCerrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblLic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 587, Short.MAX_VALUE)
                .addComponent(lblRang)
                .addGap(639, 639, 639))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLic))
                    .addComponent(lblRang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemVacunasPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVacunasPerrosActionPerformed
        if (lic == 1) {
            if (ipvp != null) {
                ipvp.dispose();
            }
            ipvp = new InternalPanelVacunasP();
            desktopMain.add(ipvp);
            ipvp.show(); 
        }else{
            JOptionPane.showMessageDialog(null, "Por favor activa tu licencia");
        }
    }//GEN-LAST:event_itemVacunasPerrosActionPerformed
    private void menuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAyudaMouseClicked
    }//GEN-LAST:event_menuAyudaMouseClicked
    private void itemLicenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLicenciaMouseClicked
    }//GEN-LAST:event_itemLicenciaMouseClicked
    private void itemLicenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLicenciaMousePressed
    }//GEN-LAST:event_itemLicenciaMousePressed

    private void itemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarActionPerformed
        if (lic == 1) {
            if (ipr != null) {
                ipr.dispose();
            }
            ipr = new InternalPanelRegistros(user);
            desktopMain.add(ipr);
            ipr.show();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor activa tu licencia");
        }
    }//GEN-LAST:event_itemRegistrarActionPerformed

    private void itemLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLicenciaActionPerformed
        Runtime cmd = Runtime.getRuntime();
        try {
            cmd.exec("C:/Windows/System32/cmd.exe /k start https://www.petlover.com.mx/licencias");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error: "+e);
        }
    }//GEN-LAST:event_itemLicenciaActionPerformed

    private void menuCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarMousePressed
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCerrarMousePressed

    private void itemSoporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSoporteMousePressed
        Runtime cmd = Runtime.getRuntime();
        try {
            JOptionPane.showMessageDialog(null, "ID para soporte: "+id);
            cmd.exec("C:/Windows/System32/cmd.exe /k start https://www.petlover.com.mx/soporte");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error: "+e);
        }
    }//GEN-LAST:event_itemSoporteMousePressed

    private void itemVacunaGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVacunaGatosActionPerformed
        if (lic == 1) {
            if (ipvg != null) {
                ipvg.dispose();
            }
            ipvg = new InternalPanelVacunasG();
            desktopMain.add(ipvg);
            ipvg.show();                      
        }else{
            JOptionPane.showMessageDialog(null, "Por favor activa tu licencia");
        }
    }//GEN-LAST:event_itemVacunaGatosActionPerformed

    private void itemConfigCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConfigCuentaActionPerformed
        if (lic == 1) {
            if (ipc != null) {
                ipc.dispose();
            }
            ipc = new InternalPanelConfi(user);
            desktopMain.add(ipc);
            ipc.show(); 
        }else{
            JOptionPane.showMessageDialog(null, "Por favor activa tu licencia");
        }
    }//GEN-LAST:event_itemConfigCuentaActionPerformed

    private void itemInstructivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstructivoActionPerformed
        Runtime cmd = Runtime.getRuntime();
        try {
            JOptionPane.showMessageDialog(null, "ID para soporte: "+id);
            cmd.exec("C:/Windows/System32/cmd.exe /k start https://www.petlover.com.mx/instrucciones");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error: "+e);
        }
    }//GEN-LAST:event_itemInstructivoActionPerformed

    private void menuBuscarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarPropActionPerformed
        if (lic == 1) {
            if (ipb != null) {
                ipb.dispose();
            }
            ipb = new InternalPanelBusqueda();
            desktopMain.add(ipb);
            ipb.show();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor activa tu licencia");
        }
    }//GEN-LAST:event_menuBuscarPropActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (lic == 1) {
            if (ipcits != null) {
                ipcits.dispose();
            }
            ipcits = new InternalPanelCitas(user);
            desktopMain.add(ipcits);
            ipcits.show();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor activa tu licencia");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
     private void ponerLicencia(int lic){
        if (lic == 1) {
            lblLic.setText("Activado");
            lblLic.setForeground(Color.green);
        }
    }
    
    private void ponerPosicion(String posc){
        switch(posc){
            case "Dev":
                lblRang.setText("Developer");
                lblRang.setForeground(Color.DARK_GRAY);
                break;
            case "Adm":
                lblRang.setText("Admin");
                lblRang.setForeground(Color.RED);
                break;
        }
    }
    
    private void verificarLicencia(String id){
        ControladorVeterinario cu = new ControladorVeterinario();
        try {
            lic = cu.BuscarLicencia(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al verificar las licencias", " Erros", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ponerActivacion(){
        if (lic == 0) {
            InternalPanelActivacion ipa = new InternalPanelActivacion(id);
            desktopMain.add(ipa);
            ipa.show(); 
        }
    }
    
    private void ponerBackground(){
       desktopMain.setBorder(new Background());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenuItem itemConfigCuenta;
    private javax.swing.JMenuItem itemInstructivo;
    private javax.swing.JMenuItem itemLicencia;
    private javax.swing.JMenuItem itemRegistrar;
    private javax.swing.JMenuItem itemSoporte;
    private javax.swing.JMenuItem itemVacunaGatos;
    private javax.swing.JMenuItem itemVacunasPerros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblLic;
    private javax.swing.JLabel lblRang;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBuscarProp;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuConfi;
    private javax.swing.JMenu menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
